version: '3'

networks:
  iotblck:
    ipam:
      config:
        - subnet: 150.0.0.0/24

services:
  discovery:
    image: disc:1.0
    networks:
      iotblck:
        ipv4_address: 150.0.0.100

  pbft:
    image: pbft:1.0
    networks:
      iotblck:
        ipv4_address: 150.0.0.101
    depends_on:
      - discovery

  storage0:
    image: sto:1.0
    networks:
      - iotblck
    depends_on:
      - discovery
  storage1:
    image: sto:1.0
    networks:
      - iotblck
    depends_on:
      - discovery
      - storage0
  storage2:
    image: sto:1.0
    networks:
      - iotblck
    depends_on:
      - discovery
      - storage1
  storage3:
    image: sto:1.0
    networks:
      - iotblck
    depends_on:
      - discovery
      - storage2
  storage4:
    image: sto:1.0
    networks:
      - iotblck
    depends_on:
      - discovery
      - storage3
  gateway0:
    image: gw:1.0
    networks:
      - iotblck
    depends_on:
      - discovery
      - storage4
  gateway1:
    image: gw:1.0
    networks:
      - iotblck
    depends_on:
      - discovery
      - gateway0
  gateway2:
    image: gw:1.0
    networks:
      - iotblck
    depends_on:
      - discovery
      - gateway1
  gateway3:
    image: gw:1.0
    networks:
      - iotblck
    depends_on:
      - discovery
      - gateway2
  gateway4:
    image: gw:1.0
    networks:
      - iotblck
    depends_on:
      - discovery
      - gateway3
