version: '3'

networks:
  iotblck:
    ipam:
      config:
        - subnet: 150.0.0.0/24

services:
  discovery:
    image: disc:1.0
    networks:
      iotblck:
        ipv4_address: 150.0.0.100

  storage0:
    image: sto:1.0
    networks:
      - iotblck
    depends_on:
      - discovery
  storage1:
    image: sto:1.0
    networks:
      - iotblck
    depends_on:
      - discovery
      - storage0
  storage2:
    image: sto:1.0
    networks:
      - iotblck
    depends_on:
      - discovery
      - storage1
  gateway0:
    image: gw:1.0
    networks:
      - iotblck
    depends_on:
      - discovery
      - storage2
  gateway1:
    image: gw:1.0
    networks:
      - iotblck
    depends_on:
      - discovery
      - gateway0
  gateway2:
    image: gw:1.0
    networks:
      - iotblck
    depends_on:
      - discovery
      - gateway1
